spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
spring.datasource:
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
  username: ${DB_USER}
  password: ${DB_PASS}
spring.cache.cache-names: shortLink
spring.cache.caffeine.spec: maximumSize=500,expireAfterAccess=3600s