spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: ${DB_USER}
    password: ${DB_PASS}
  cache:
    cache-names: shortLink
    caffeine:
      spec: maximumSize=500,expireAfterAccess=3600s
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

google.recaptcha.v3:
  secret: ${RECAPTCHA_V3_SECRET}
  verify: true
  min: 0.7
  action: create
  
server:
  tomcat:
    threads:
      max: ${HTTP_MAX_THREADS:10}
