name: Build and Push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get Maven artifact
        id: get_artifact
        working-directory: "./"
        run: |
          NAME=$( mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout )
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=name::$NAME"
          echo "::set-output name=version::$VERSION"

      - name: Build Native Image
        run: mvn clean spring-boot:build-image

      - name: Push Image
        env:
          IMAGE_NAME: ${{ steps.get_artifact.outputs.name }}
          VERSION: ${{ steps.get_artifact.outputs.version }}
        run: |
          docker image ls
          docker tag $IMAGE_NAME:$VERSION jhinze/$IMAGE_NAME:$VERSION
          docker push jhinze/$IMAGE_NAME:$VERSION
          docker tag jhinze/$IMAGE_NAME:$VERSION jhinze/$IMAGE_NAME:latest
          docker push jhinze/$IMAGE_NAME:latest
